version: '3.2'

services:
  nginx:
    image: jwilder/nginx-proxy
    volumes:
      - ./cert:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock
    ports:
      - "80:80"
      - "443:443"

  gocd:
    image: gocd/gocd-server:v19.2.0
    volumes:
      - ./scripts/3.user.sh:/docker-entrypoint.d/user.sh
      - ./scripts/2.pre-conf.sh:/pre-conf.sh
      - ./secrets/password.properties:/etc/go-users
    environment:
      - VIRTUAL_HOST=cicd.sunzhongmou.com
      - GOCD_PLUGIN_INSTALL_docker-elastic-agents=https://github.com/gocd-contrib/docker-elastic-agents/releases/download/v2.2.0/docker-elastic-agents-2.2.0-187.jar
    ports:
      - "8013:8153"