version: '3.2'

services:
#  nginx:
#    image: jwilder/nginx-proxy
#    volumes:
#      - ./certs:/etc/nginx/certs
#      - /var/run/docker.sock:/tmp/docker.sock
#    ports:
#      - "80:80"
#      - "443:443"

  gocd:
    image: gocd/gocd-server:v19.2.0
    volumes:
      - ./scripts/3.user.sh:/docker-entrypoint.d/user.sh
      - ./scripts/2.pre-conf.sh:/pre-conf.sh
      - ./secrets/password.properties:/etc/go-users
    environment:
      - VIRTUAL_HOST=cicd.sunwei.com
      - GOCD_PLUGIN_INSTALL_docker-elastic-agents=https://github.com/gocd-contrib/docker-elastic-agents/releases/download/v0.8.0/docker-elastic-agents-0.8.0.jar
    ports:
      - "8153:8153"
      - "8154:8154"